import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Furnitore",
  description: "Generated by create next app",
  icons: "../public/images/logo/Meubel House_Logos-05.svg",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${montserrat.className} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
