import stylish_coffee_chair from "@/public/images/assets/stylish_coffee_chair.svg";
import leviosa from "@/public/images/assets/leviosa.svg";
import lolito from "@/public/images/assets/lolito.svg";
import respira from "@/public/images/assets/respira.svg";
import grifo from "@/public/images/assets/grifo.svg";
import muggo from "@/public/images/assets/muggo.svg";
import pingky from "@/public/images/assets/pingky.svg";
import potty from "@/public/images/assets/potty.svg";

export const products = [
  {
    id: 1,
    name: "Slytherin",
    category: "Stylish coffee table",
    price: "250",
    oldPrice: "150",
    discount: "30%",
    image: stylish_coffee_chair,
    new: false,
  },
  {
    id: 2,
    name: "Leviosa",
    category: "Stylish cafe chair",
    price: "1.000",
    oldPrice: "2.000",
    discount: "50%",
    image: leviosa,
    new: false,
  },
  {
    id: 3,
    name: "Lolito",
    category: "Luxury big sofa",
    price: "7.000",
    oldPrice: "14.000",
    discount: "50%",
    image: lolito,
    new: false,
  },
  {
    id: 4,
    name: "Respira",
    category: "Outdoor bar table and stool",
    price: "5.000",
    oldPrice: "",
    discount: "",
    image: respira,
    new: true,
  },
  {
    id: 5,
    name: "Grifo",
    category: "Night lamp",
    price: "70",
    oldPrice: "",
    discount: "",
    image: grifo,
    new: true,
  },
  {
    id: 6,
    name: "Muggo",
    category: "Small couch",
    price: "750",
    oldPrice: "",
    discount: "",
    image: muggo,
    new: true,
  },
  {
    id: 7,
    name: "Pingky",
    category: "Cute couch",
    price: "10.000",
    oldPrice: "20.000",
    discount: "50%",
    image: pingky,
    new: false,
  },
  {
    id: 8,
    name: "Potty",
    category: "Minimalist couch",
    price: "9.000",
    oldPrice: "",
    discount: "",
    image: potty,
    new: true,
  },
  {
    id: 9,
    name: "Glimmer",
    category: "Modern chandelier",
    price: "500",
    oldPrice: "750",
    discount: "33%",
    image: potty,
    new: false,
  },
  {
    id: 10,
    name: "Terra",
    category: "Terrarium coffee table",
    price: "300",
    oldPrice: "",
    discount: "",
    image: grifo,
    new: true,
  },
  {
    id: 11,
    name: "Aqua",
    category: "Glass vase",
    price: "80",
    oldPrice: "",
    discount: "",
    image: potty,
    new: true,
  },
  {
    id: 12,
    name: "Cosmic",
    category: "Space-themed rug",
    price: "200",
    oldPrice: "300",
    discount: "33%",
    image: pingky,
    new: false,
  },
  {
    id: 13,
    name: "Nova",
    category: "LED pendant light",
    price: "150",
    oldPrice: "",
    discount: "",
    image: potty,
    new: true,
  },
  {
    id: 14,
    name: "Rustico",
    category: "Rustic dining table",
    price: "1.200",
    oldPrice: "1.500",
    discount: "20%",
    image: pingky,
    new: false,
  },
  {
    id: 15,
    name: "Nebula",
    category: "Galaxy-inspired lamp",
    price: "100",
    oldPrice: "",
    discount: "",
    image: muggo,
    new: true,
  },
  {
    id: 16,
    name: "Serenity",
    category: "Zen garden set",
    price: "400",
    oldPrice: "",
    discount: "",
    image: potty,
    new: true,
  },
  {
    id: 17,
    name: "Zenith",
    category: "Minimalist bookshelf",
    price: "600",
    oldPrice: "800",
    discount: "25%",
    image: muggo,
    new: false,
  },
  {
    id: 18,
    name: "Eclipse",
    category: "Dark-themed curtains",
    price: "120",
    oldPrice: "",
    discount: "",
    image: grifo,
    new: true,
  },
  {
    id: 19,
    name: "Lunar",
    category: "Moon-shaped side table",
    price: "180",
    oldPrice: "",
    discount: "",
    image: stylish_coffee_chair,
    new: true,
  },
  {
    id: 20,
    name: "Aurora",
    category: "Northern Lights wall art",
    price: "90",
    oldPrice: "",
    discount: "",
    image: leviosa,
    new: true,
  },
  {
    id: 21,
    name: "Stella",
    category: "Star-patterned rug",
    price: "250",
    oldPrice: "300",
    discount: "17%",
    image: lolito,
    new: false,
  },
  {
    id: 22,
    name: "Tropicana",
    category: "Tropical-themed cushion",
    price: "50",
    oldPrice: "",
    discount: "",
    image: respira,
    new: true,
  },
  {
    id: 23,
    name: "Cascade",
    category: "Waterfall desk lamp",
    price: "120",
    oldPrice: "",
    discount: "",
    image: grifo,
    new: true,
  },
  {
    id: 24,
    name: "Mystic",
    category: "Crystal ball decor",
    price: "70",
    oldPrice: "",
    discount: "",
    image: muggo,
    new: true,
  },
  {
    id: 25,
    name: "Harmony",
    category: "Bamboo wind chime",
    price: "40",
    oldPrice: "",
    discount: "",
    image: pingky,
    new: true,
  },
  {
    id: 26,
    name: "Tranquil",
    category: "Zen garden fountain",
    price: "300",
    oldPrice: "",
    discount: "",
    image: potty,
    new: true,
  },
  {
    id: 27,
    name: "Solaris",
    category: "Sunburst wall mirror",
    price: "200",
    oldPrice: "",
    discount: "",
    image: stylish_coffee_chair, // Reusing for demonstration
    new: true,
  },
  {
    id: 28,
    name: "Glow",
    category: "Glow-in-the-dark stickers",
    price: "15",
    oldPrice: "",
    discount: "",
    image: leviosa, // Reusing for demonstration
    new: true,
  },
];
